import {
  set_trial_context,
  type StimBank,
  type TaskSettings,
  type TrialBuilder,
  type TrialSnapshot
} from "psyflow-web";

import { normalizeRule, sampleCardTrialSpec } from "./utils";

export function run_trial(
  trial: TrialBuilder,
  condition: string,
  context: {
    settings: TaskSettings;
    stimBank: StimBank;
    block_id: string;
    block_idx: number;
  }
): TrialBuilder {
  const { settings, stimBank, block_id, block_idx } = context;
  const rule = normalizeRule(String(condition));
  const key_list = ((settings.key_list as string[]) ?? ["1", "2", "3", "4"]).map(String);
  if (key_list.length !== 4) {
    throw new Error(`H000016 requires 4 response keys, got ${JSON.stringify(key_list)}`);
  }
  if (!Array.isArray(settings.block_seed) || settings.block_seed.length === 0) {
    throw new Error("H000016 requires task.block_seed to be generated by TaskSettings.");
  }
  const blockSeed = Number(settings.block_seed[block_idx] ?? settings.overall_seed ?? 2025);
  const trialNumericId = Number(trial.trial_id);
  const trialSeed = blockSeed * 1000 + (Number.isFinite(trialNumericId) ? trialNumericId : 0);
  const trialSpec = sampleCardTrialSpec(rule, {
    key_list,
    seed: trialSeed
  });
  const trigger_map = (settings.triggers ?? {}) as Record<string, unknown>;
  const cueDuration = Number(settings.cue_duration ?? 0.4);
  const anticipationDuration = Number(settings.anticipation_duration ?? 0.2);
  const targetDuration = Number(settings.target_duration ?? 2);
  const feedbackDuration = Number(settings.feedback_duration ?? 0.6);
  const itiDuration = Number(settings.iti_duration ?? 0.3);

  const cueUnit = trial.unit("rule_cue").addStim(stimBank.get(`rule_cue_${rule}`));
  set_trial_context(cueUnit, {
    trial_id: trial.trial_id,
    phase: "rule_cue",
    deadline_s: cueDuration,
    valid_keys: [],
    block_id,
    condition_id: trialSpec.condition_id,
    task_factors: {
      rule,
      stage: "rule_cue",
      block_idx
    },
    stim_id: `rule_cue_${rule}`
  });
  cueUnit
    .show({
      duration: cueDuration
    })
    .to_dict();

  const preChoiceFixation = trial.unit("pre_choice_fixation").addStim(stimBank.get("fixation"));
  set_trial_context(preChoiceFixation, {
    trial_id: trial.trial_id,
    phase: "pre_choice_fixation",
    deadline_s: anticipationDuration,
    valid_keys: [],
    block_id,
    condition_id: trialSpec.condition_id,
    task_factors: {
      rule,
      stage: "pre_choice_fixation",
      block_idx
    },
    stim_id: "fixation"
  });
  preChoiceFixation
    .show({
      duration: anticipationDuration
    })
    .to_dict();

  const choiceDisplay = trial
    .unit("card_choice_response")
    .addStim(stimBank.rebuild("target_card", { image: trialSpec.target_image }))
    .addStim(stimBank.get("ref_card_1"))
    .addStim(stimBank.get("ref_card_2"))
    .addStim(stimBank.get("ref_card_3"))
    .addStim(stimBank.get("ref_card_4"));
  set_trial_context(choiceDisplay, {
    trial_id: trial.trial_id,
    phase: "card_choice_response",
    deadline_s: targetDuration,
    valid_keys: [...key_list],
    block_id,
    condition_id: trialSpec.condition_id,
    task_factors: {
      rule,
      target_color: trialSpec.target_color,
      target_shape: trialSpec.target_shape,
      target_number: trialSpec.target_number,
      correct_key: trialSpec.correct_key,
      target_image: trialSpec.target_image,
      trial_seed: trialSeed,
      stage: "card_choice_response",
      block_idx
    },
    stim_id: "target_card"
  });
  choiceDisplay
    .captureResponse({
      keys: key_list,
      correct_keys: [trialSpec.correct_key],
      duration: targetDuration,
      response_trigger: Number(trigger_map.key_press ?? 40),
      timeout_trigger: Number(trigger_map.no_response ?? 41),
      terminate_on_response: true
    })
    .set_state({
      rule,
      condition_id: trialSpec.condition_id,
      trial_seed: trialSeed,
      target_color: trialSpec.target_color,
      target_shape: trialSpec.target_shape,
      target_number: trialSpec.target_number,
      target_image: trialSpec.target_image,
      target_correct_key: trialSpec.correct_key,
      target_response_key: choiceDisplay.ref<string>("response"),
      target_response: choiceDisplay.ref<string>("response"),
      target_hit: choiceDisplay.ref<boolean>("hit"),
      target_rt: choiceDisplay.ref<number | null>("rt")
    })
    .to_dict();

  const feedbackUnit = trial
    .unit("choice_feedback")
    .addStim((snapshot: TrialSnapshot) =>
      stimBank.get(snapshot.units.card_choice_response?.hit === true ? "feedback_correct" : "feedback_incorrect")
    );
  set_trial_context(feedbackUnit, {
    trial_id: trial.trial_id,
    phase: "choice_feedback",
    deadline_s: feedbackDuration,
    valid_keys: [],
    block_id,
    condition_id: trialSpec.condition_id,
    task_factors: {
      rule,
      correct_key: trialSpec.correct_key,
      stage: "choice_feedback",
      block_idx
    },
    stim_id: "choice_feedback"
  });
  feedbackUnit
    .show({ duration: feedbackDuration })
    .set_state({
      hit: choiceDisplay.ref<boolean>("hit"),
      feedback_label: (snapshot: TrialSnapshot) =>
        snapshot.units.card_choice_response?.hit === true ? "正确" : "错误",
      delta: (snapshot: TrialSnapshot) => (snapshot.units.card_choice_response?.hit === true ? 1 : 0)
    })
    .to_dict();

  const itiUnit = trial.unit("iti").addStim(stimBank.get("fixation"));
  set_trial_context(itiUnit, {
    trial_id: trial.trial_id,
    phase: "iti",
    deadline_s: itiDuration,
    valid_keys: [],
    block_id,
    condition_id: trialSpec.condition_id,
    task_factors: {
      rule,
      stage: "iti",
      block_idx
    },
    stim_id: "fixation"
  });
  itiUnit.show({ duration: itiDuration }).to_dict();

  trial.finalize((snapshot, _runtime, helpers) => {
    const hit = snapshot.units.card_choice_response?.hit === true;
    helpers.setTrialState("rule", rule);
    helpers.setTrialState("condition_id", trialSpec.condition_id);
    helpers.setTrialState("target_correct_key", trialSpec.correct_key);
    helpers.setTrialState("target_response_key", snapshot.units.card_choice_response?.response ?? null);
    helpers.setTrialState("target_response", snapshot.units.card_choice_response?.response ?? null);
    helpers.setTrialState("target_hit", hit);
    helpers.setTrialState("target_rt", snapshot.units.card_choice_response?.rt ?? null);
    helpers.setTrialState("feedback_delta", hit ? 1 : 0);
  });

  return trial;
}
